CREATE TABLE IF NOT EXISTS job_position (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '岗位主键',
    source VARCHAR(50) NOT NULL COMMENT '数据来源',
    source_job_id VARCHAR(100) NOT NULL COMMENT '来源平台岗位ID',
    source_url VARCHAR(1000) NOT NULL COMMENT '岗位原始链接',
    job_name VARCHAR(200) NOT NULL COMMENT '原始岗位名称',
    standard_job VARCHAR(100) DEFAULT NULL COMMENT '标准岗位名称',
    job_category VARCHAR(50) DEFAULT NULL COMMENT '岗位类别',
    company_name VARCHAR(200) NOT NULL COMMENT '公司名称',
    province VARCHAR(50) DEFAULT NULL COMMENT '省份',
    city VARCHAR(50) DEFAULT NULL COMMENT '城市',
    district VARCHAR(50) DEFAULT NULL COMMENT '区县',
    region VARCHAR(20) DEFAULT NULL COMMENT '所属区域',
    city_level VARCHAR(20) DEFAULT NULL COMMENT '城市等级',
    salary_text VARCHAR(100) DEFAULT NULL COMMENT '薪资原文',
    salary_min DECIMAL(12, 2) DEFAULT NULL COMMENT '最低月薪（元）',
    salary_max DECIMAL(12, 2) DEFAULT NULL COMMENT '最高月薪（元）',
    salary_avg DECIMAL(12, 2) DEFAULT NULL COMMENT '平均月薪（元）',
    salary_months INT DEFAULT NULL COMMENT '年薪月数',
    salary_unit VARCHAR(20) DEFAULT NULL COMMENT '薪资单位',
    salary_negotiable TINYINT NOT NULL DEFAULT 0 COMMENT '是否面议：0否，1是',
    education_text VARCHAR(100) DEFAULT NULL COMMENT '学历要求原文',
    education VARCHAR(20) DEFAULT NULL COMMENT '标准学历',
    experience VARCHAR(50) DEFAULT NULL COMMENT '工作经验要求',
    major_text VARCHAR(500) DEFAULT NULL COMMENT '专业要求原文',
    description MEDIUMTEXT COMMENT '岗位描述',
    publish_time DATETIME DEFAULT NULL COMMENT '岗位发布时间',
    collect_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '采集时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    job_status TINYINT NOT NULL DEFAULT 1 COMMENT '岗位状态：0未知，1招聘中，2已关闭',
    is_delete TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否，1是',
    PRIMARY KEY (id),
    UNIQUE KEY uk_job_position_source_job (source, source_job_id),
    KEY idx_job_position_city (city),
    KEY idx_job_position_standard_job (standard_job),
    KEY idx_job_position_education (education),
    KEY idx_job_position_publish_time (publish_time),
    KEY idx_job_position_status (job_status, is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='招聘岗位明细表';
